use anyhow::{Context, Result};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use crate::codex;
use crate::gitx::Repo;
use crate::state::Allocation;
use crate::util::sh_quote;
use crate::worktree;

pub fn vars(repo: &Repo, alloc: &Allocation) -> BTreeMap<String, String> {
    let wt_path = Path::new(&alloc.path);
    let mut vars = BTreeMap::new();

    vars.insert("WRT_NAME".into(), alloc.name.clone());
    vars.insert("WRT_BRANCH".into(), alloc.branch.clone());
    vars.insert("WRT_PORT_BLOCK".into(), alloc.block.to_string());
    vars.insert("WRT_PORT_OFFSET".into(), alloc.offset.to_string());
    vars.insert(
        "WRT_ROOT".into(),
        repo.managed_root.to_string_lossy().to_string(),
    );
    vars.insert(
        "WRT_WORKTREE_PATH".into(),
        wt_path.to_string_lossy().to_string(),
    );
    vars.insert(
        "WRT_MAIN_PATH".into(),
        repo.main_worktree.to_string_lossy().to_string(),
    );
    vars.insert(
        "COMPOSE_PROJECT_NAME".into(),
        compose_project_name(repo, alloc),
    );

    if let Some(discovery) = discovery_for(repo, wt_path) {
        add_service_vars(&mut vars, &discovery, alloc.offset);
    }

    vars
}

pub fn write_env_file(repo: &Repo, wt_path: &Path, alloc: &Allocation) -> Result<()> {
    let p = wt_path.join(".wrt.env");
    let mut out = "# Generated by wrt. Safe to edit; re-running wrt may overwrite.\n".to_string();
    for (k, v) in vars(repo, alloc) {
        out.push_str(&k);
        out.push('=');
        out.push_str(&sh_quote(&v));
        out.push('\n');
    }
    fs::write(&p, out.as_bytes()).with_context(|| format!("write {}", p.display()))?;
    Ok(())
}

pub fn print_exports(repo: &Repo, alloc: &Allocation) {
    for (k, v) in vars(repo, alloc) {
        println!("export {k}={}", sh_quote(&v));
    }
}

pub fn apply_to_command_env(command: &mut std::process::Command, repo: &Repo, alloc: &Allocation) {
    for (k, v) in vars(repo, alloc) {
        command.env(k, v);
    }
}

fn discovery_for(repo: &Repo, wt_path: &Path) -> Option<codex::Discovery> {
    let local = wt_path.join(".wrt.json");
    if let Some(d) = read_discovery(&local) {
        return Some(d);
    }

    let fallback = repo.config_root.join(".wrt.json");
    if fallback != local {
        return read_discovery(&fallback);
    }
    None
}

fn read_discovery(path: &Path) -> Option<codex::Discovery> {
    let s = fs::read_to_string(path).ok()?;
    serde_json::from_str(&s).ok()
}

fn add_service_vars(
    vars: &mut BTreeMap<String, String>,
    discovery: &codex::Discovery,
    offset: i32,
) {
    for service in &discovery.services {
        let Some(base_port) = service.base_port else {
            continue;
        };
        let port = base_port + offset;
        if !(1..=65535).contains(&port) {
            continue;
        }

        let service_key = sanitize_env_part(&service.name);
        vars.insert(format!("WRT_SERVICE_{service_key}_PORT"), port.to_string());
        vars.insert(
            format!("WRT_SERVICE_{service_key}_URL"),
            format!("http://localhost:{port}"),
        );

        if let Some(port_env) = service.port_env.as_deref() {
            let port_env = port_env.trim();
            if is_valid_env_name(port_env) {
                vars.insert(port_env.to_string(), port.to_string());
            }
        }

        if let Some(url_env) = service.url_env.as_deref() {
            let url_env = url_env.trim();
            if is_valid_env_name(url_env) {
                vars.insert(url_env.to_string(), format!("http://localhost:{port}"));
            }
        }
    }
}

fn compose_project_name(repo: &Repo, alloc: &Allocation) -> String {
    let root_name = repo
        .managed_root
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("repo");
    let mut out = worktree::slug(&format!("wrt-{root_name}-{}", alloc.name));
    if out.len() > 63 {
        out.truncate(63);
        out = out.trim_matches('-').to_string();
    }
    if out.is_empty() {
        "wrt".to_string()
    } else {
        out
    }
}

fn sanitize_env_part(s: &str) -> String {
    let mut out = String::new();
    let mut prev_sep = false;
    for ch in s.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_uppercase());
            prev_sep = false;
        } else if !prev_sep {
            out.push('_');
            prev_sep = true;
        }
    }
    let out = out.trim_matches('_').to_string();
    if out.is_empty() {
        "SERVICE".to_string()
    } else {
        out
    }
}

fn is_valid_env_name(s: &str) -> bool {
    let mut chars = s.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if first != '_' && !first.is_ascii_alphabetic() {
        return false;
    }
    chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::gitx::Repo;
    use crate::state::Allocation;
    use tempfile::TempDir;

    fn repo(root: &Path) -> Repo {
        Repo {
            root: root.to_path_buf(),
            common_dir: root.join(".git"),
            managed_root: root.to_path_buf(),
            invocation_root: Some(root.to_path_buf()),
            config_root: root.to_path_buf(),
            main_worktree: root.to_path_buf(),
            worktree_parent: root.to_path_buf(),
        }
    }

    fn alloc(path: &Path) -> Allocation {
        Allocation {
            name: "x".into(),
            branch: "x".into(),
            path: path.to_string_lossy().to_string(),
            block: 1,
            offset: 100,
            status: "active".into(),
            created_at: "now".into(),
        }
    }

    #[test]
    fn includes_base_and_discovered_service_vars() {
        let td = TempDir::new().unwrap();
        fs::write(
            td.path().join(".wrt.json"),
            r#"{
  "version": 1,
  "port_block_size": 100,
  "package_manager": { "name": "unknown", "install_command": ["npm","install"], "notes": null },
  "services": [{ "name": "web app", "kind": "web", "dev_command": ["npm","run","dev"], "base_port": 3000, "port_env": "PORT", "url_env": "APP_URL", "notes": null }],
  "database": { "detected": false, "kind": null, "migrate_command": null, "seed_command": null, "reset_command": null, "notes": null },
  "supabase": { "detected": false, "config_path": null, "start_command": null, "base_ports": null, "notes": null },
  "notes": null
}
"#,
        )
        .unwrap();

        let vars = vars(&repo(td.path()), &alloc(td.path()));
        assert_eq!(vars.get("WRT_NAME").unwrap(), "x");
        assert_eq!(vars.get("WRT_PORT_OFFSET").unwrap(), "100");
        assert_eq!(vars.get("PORT").unwrap(), "3100");
        assert_eq!(vars.get("APP_URL").unwrap(), "http://localhost:3100");
        assert_eq!(vars.get("WRT_SERVICE_WEB_APP_PORT").unwrap(), "3100");
    }
}
