use anyhow::{Context, Result};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;
use std::process::Command;

use crate::codex;
use crate::gitx::Repo;
use crate::state::{Allocation, State};
use crate::supabase;
use crate::util::sh_quote;
use crate::worktree;

const SUPABASE_BLOCK_START: &str = "# >>> wrt supabase (generated)";
const SUPABASE_BLOCK_END: &str = "# <<< wrt supabase";

pub fn vars(repo: &Repo, state: &State, alloc: &Allocation) -> Result<BTreeMap<String, String>> {
    let wt_path = Path::new(&alloc.path);
    let mut vars = BTreeMap::new();

    vars.insert("WRT_NAME".into(), alloc.name.clone());
    vars.insert("WRT_BRANCH".into(), alloc.branch.clone());
    vars.insert("WRT_PORT_BLOCK".into(), alloc.block.to_string());
    vars.insert("WRT_PORT_OFFSET".into(), alloc.offset.to_string());
    vars.insert(
        "WRT_ROOT".into(),
        repo.managed_root.to_string_lossy().to_string(),
    );
    vars.insert(
        "WRT_WORKTREE_PATH".into(),
        wt_path.to_string_lossy().to_string(),
    );
    vars.insert(
        "WRT_MAIN_PATH".into(),
        repo.main_worktree.to_string_lossy().to_string(),
    );
    vars.insert(
        "COMPOSE_PROJECT_NAME".into(),
        compose_project_name(repo, alloc),
    );

    if let Some(discovery) = discovery_for(repo, wt_path) {
        add_service_vars(&mut vars, &discovery, alloc.offset);
    }

    if let Some((owner, target)) = supabase::allocation_target(state, alloc)? {
        let status = supabase::status_env(Path::new(&owner.path), &target)?;
        add_supabase_vars(&mut vars, &status);
        vars.insert("WRT_SUPABASE_OWNER".into(), owner.name.clone());
    }

    Ok(vars)
}

pub fn sync_env_files(
    repo: &Repo,
    state: &State,
    wt_path: &Path,
    alloc: &Allocation,
) -> Result<()> {
    let vars = vars(repo, state, alloc)?;
    write_wrt_env_file(wt_path, &vars)?;

    let supabase_vars: BTreeMap<String, String> = vars
        .iter()
        .filter(|(key, _)| is_supabase_env_name(key))
        .map(|(key, value)| (key.clone(), value.clone()))
        .collect();
    let target = supabase::allocation_target(state, alloc)?
        .map(|(_, target)| target)
        .or_else(|| {
            state
                .root
                .as_ref()
                .and_then(|root| root.supabase_config_path.as_deref())
                .and_then(|path| supabase::Target::from_config_path(path).ok())
        });

    let mut env_paths = vec![(wt_path.join(".env"), std::path::PathBuf::from(".env"))];
    if let Some(target) = target {
        let relative = target.relative_workdir().join(".env");
        let nested = wt_path.join(&relative);
        if nested != env_paths[0].0 {
            env_paths.push((nested, relative));
        }
    }

    for (path, relative) in env_paths {
        if supabase_vars.is_empty() {
            remove_managed_block(&path)?;
            remove_managed_block(&path.with_file_name(".env.local"))?;
        } else {
            let output_path = env_output_path(wt_path, &path, &relative)?;
            if output_path != path {
                remove_managed_block(&path)?;
            }
            write_managed_block(&output_path, &supabase_vars)?;
        }
    }
    Ok(())
}

fn write_wrt_env_file(wt_path: &Path, vars: &BTreeMap<String, String>) -> Result<()> {
    let p = wt_path.join(".wrt.env");
    let mut out = "# Generated by wrt. Safe to edit; re-running wrt may overwrite.\n".to_string();
    for (k, v) in vars {
        out.push_str(k);
        out.push('=');
        out.push_str(&sh_quote(v));
        out.push('\n');
    }
    fs::write(&p, out.as_bytes()).with_context(|| format!("write {}", p.display()))?;
    Ok(())
}

pub fn print_exports(repo: &Repo, state: &State, alloc: &Allocation) -> Result<()> {
    for (k, v) in vars(repo, state, alloc)? {
        println!("export {k}={}", sh_quote(&v));
    }
    Ok(())
}

pub fn apply_to_command_env(
    command: &mut std::process::Command,
    repo: &Repo,
    state: &State,
    alloc: &Allocation,
) -> Result<()> {
    for (k, v) in vars(repo, state, alloc)? {
        command.env(k, v);
    }
    Ok(())
}

fn add_supabase_vars(vars: &mut BTreeMap<String, String>, status: &BTreeMap<String, String>) {
    copy_status_var(vars, status, "API_URL", "SUPABASE_URL");
    copy_status_var(vars, status, "ANON_KEY", "SUPABASE_ANON_KEY");
    copy_status_var(
        vars,
        status,
        "SERVICE_ROLE_KEY",
        "SUPABASE_SERVICE_ROLE_KEY",
    );
    copy_status_var(vars, status, "JWT_SECRET", "SUPABASE_JWT_SECRET");
    copy_status_var(vars, status, "DB_URL", "SUPABASE_DB_URL");
    copy_status_var(vars, status, "DB_URL", "DATABASE_URL");
    copy_status_var(vars, status, "STUDIO_URL", "SUPABASE_STUDIO_URL");
    copy_status_var(vars, status, "GRAPHQL_URL", "SUPABASE_GRAPHQL_URL");
    copy_status_var(vars, status, "INBUCKET_URL", "SUPABASE_INBUCKET_URL");
}

fn copy_status_var(
    vars: &mut BTreeMap<String, String>,
    status: &BTreeMap<String, String>,
    source: &str,
    destination: &str,
) {
    if let Some(value) = status.get(source) {
        vars.insert(destination.to_string(), value.clone());
    }
}

fn env_output_path(wt_path: &Path, path: &Path, relative: &Path) -> Result<std::path::PathBuf> {
    if !is_tracked(wt_path, relative)? {
        return Ok(path.to_path_buf());
    }

    let local_path = path.with_file_name(".env.local");
    let local_relative = relative.with_file_name(".env.local");
    if is_tracked(wt_path, &local_relative)? {
        anyhow::bail!(
            "both {} and {} are tracked; refusing to write Supabase credentials",
            relative.display(),
            local_relative.display()
        );
    }
    Ok(local_path)
}

fn is_tracked(wt_path: &Path, relative: &Path) -> Result<bool> {
    let output = Command::new("git")
        .args(["ls-files", "--error-unmatch", "--"])
        .arg(relative)
        .current_dir(wt_path)
        .output()
        .with_context(|| format!("check whether {} is tracked", relative.display()))?;
    Ok(output.status.success())
}

fn is_supabase_env_name(key: &str) -> bool {
    key.starts_with("SUPABASE_") || key == "DATABASE_URL"
}

fn write_managed_block(path: &Path, vars: &BTreeMap<String, String>) -> Result<()> {
    let mut input = match fs::read_to_string(path) {
        Ok(input) => input,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(error) => return Err(error).with_context(|| format!("read {}", path.display())),
    };
    remove_block_from_string(&mut input)?;
    if !input.is_empty() && !input.ends_with('\n') {
        input.push('\n');
    }
    if !input.is_empty() && !input.ends_with("\n\n") {
        input.push('\n');
    }
    input.push_str(SUPABASE_BLOCK_START);
    input.push('\n');
    for (key, value) in vars {
        input.push_str(key);
        input.push('=');
        input.push_str(&sh_quote(value));
        input.push('\n');
    }
    input.push_str(SUPABASE_BLOCK_END);
    input.push('\n');
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("mkdir {}", parent.display()))?;
    }
    fs::write(path, input).with_context(|| format!("write {}", path.display()))
}

fn remove_managed_block(path: &Path) -> Result<()> {
    let mut input = match fs::read_to_string(path) {
        Ok(input) => input,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(error) => return Err(error).with_context(|| format!("read {}", path.display())),
    };
    if !remove_block_from_string(&mut input)? {
        return Ok(());
    }
    fs::write(path, input).with_context(|| format!("write {}", path.display()))
}

fn remove_block_from_string(input: &mut String) -> Result<bool> {
    let Some(start) = input.find(SUPABASE_BLOCK_START) else {
        return Ok(false);
    };
    let rest = &input[start..];
    let end = rest
        .find(SUPABASE_BLOCK_END)
        .ok_or_else(|| anyhow::anyhow!("unterminated wrt Supabase block"))?;
    let mut end = start + end + SUPABASE_BLOCK_END.len();
    if input.as_bytes().get(end) == Some(&b'\r') {
        end += 1;
    }
    if input.as_bytes().get(end) == Some(&b'\n') {
        end += 1;
    }
    input.replace_range(start..end, "");
    while input.ends_with("\n\n") {
        input.pop();
    }
    Ok(true)
}

fn discovery_for(repo: &Repo, wt_path: &Path) -> Option<codex::Discovery> {
    let local = wt_path.join(".wrt.json");
    if let Some(d) = read_discovery(&local) {
        return Some(d);
    }

    let fallback = repo.config_root.join(".wrt.json");
    if fallback != local {
        return read_discovery(&fallback);
    }
    None
}

fn read_discovery(path: &Path) -> Option<codex::Discovery> {
    let s = fs::read_to_string(path).ok()?;
    serde_json::from_str(&s).ok()
}

fn add_service_vars(
    vars: &mut BTreeMap<String, String>,
    discovery: &codex::Discovery,
    offset: i32,
) {
    for service in &discovery.services {
        let Some(base_port) = service.base_port else {
            continue;
        };
        let port = base_port + offset;
        if !(1..=65535).contains(&port) {
            continue;
        }

        let service_key = sanitize_env_part(&service.name);
        vars.insert(format!("WRT_SERVICE_{service_key}_PORT"), port.to_string());
        vars.insert(
            format!("WRT_SERVICE_{service_key}_URL"),
            format!("http://localhost:{port}"),
        );

        if let Some(port_env) = service.port_env.as_deref() {
            let port_env = port_env.trim();
            if is_valid_env_name(port_env) {
                vars.insert(port_env.to_string(), port.to_string());
            }
        }

        if let Some(url_env) = service.url_env.as_deref() {
            let url_env = url_env.trim();
            if is_valid_env_name(url_env) {
                vars.insert(url_env.to_string(), format!("http://localhost:{port}"));
            }
        }
    }
}

fn compose_project_name(repo: &Repo, alloc: &Allocation) -> String {
    let root_name = repo
        .managed_root
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("repo");
    let mut out = worktree::slug(&format!("wrt-{root_name}-{}", alloc.name));
    if out.len() > 63 {
        out.truncate(63);
        out = out.trim_matches('-').to_string();
    }
    if out.is_empty() {
        "wrt".to_string()
    } else {
        out
    }
}

fn sanitize_env_part(s: &str) -> String {
    let mut out = String::new();
    let mut prev_sep = false;
    for ch in s.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_uppercase());
            prev_sep = false;
        } else if !prev_sep {
            out.push('_');
            prev_sep = true;
        }
    }
    let out = out.trim_matches('_').to_string();
    if out.is_empty() {
        "SERVICE".to_string()
    } else {
        out
    }
}

fn is_valid_env_name(s: &str) -> bool {
    let mut chars = s.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if first != '_' && !first.is_ascii_alphabetic() {
        return false;
    }
    chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::gitx::Repo;
    use crate::state::{Allocation, State, SupabaseAllocation};
    use tempfile::TempDir;

    fn repo(root: &Path) -> Repo {
        Repo {
            root: root.to_path_buf(),
            common_dir: root.join(".git"),
            managed_root: root.to_path_buf(),
            invocation_root: Some(root.to_path_buf()),
            config_root: root.to_path_buf(),
            main_worktree: root.to_path_buf(),
            worktree_parent: root.to_path_buf(),
        }
    }

    fn alloc(path: &Path) -> Allocation {
        Allocation {
            name: "x".into(),
            branch: "x".into(),
            path: path.to_string_lossy().to_string(),
            block: 1,
            offset: 100,
            status: "active".into(),
            created_at: "now".into(),
            supabase: SupabaseAllocation::None,
        }
    }

    #[test]
    fn includes_base_and_discovered_service_vars() {
        let td = TempDir::new().unwrap();
        fs::write(
            td.path().join(".wrt.json"),
            r#"{
  "version": 1,
  "port_block_size": 100,
  "package_manager": { "name": "unknown", "install_command": ["npm","install"], "notes": null },
  "services": [{ "name": "web app", "kind": "web", "dev_command": ["npm","run","dev"], "base_port": 3000, "port_env": "PORT", "url_env": "APP_URL", "notes": null }],
  "database": { "detected": false, "kind": null, "migrate_command": null, "seed_command": null, "reset_command": null, "notes": null },
  "supabase": { "detected": false, "config_path": null, "start_command": null, "base_ports": null, "notes": null },
  "notes": null
}
"#,
        )
        .unwrap();

        let vars = vars(&repo(td.path()), &State::empty(), &alloc(td.path())).unwrap();
        assert_eq!(vars.get("WRT_NAME").unwrap(), "x");
        assert_eq!(vars.get("WRT_PORT_OFFSET").unwrap(), "100");
        assert_eq!(vars.get("PORT").unwrap(), "3100");
        assert_eq!(vars.get("APP_URL").unwrap(), "http://localhost:3100");
        assert_eq!(vars.get("WRT_SERVICE_WEB_APP_PORT").unwrap(), "3100");
    }

    #[test]
    fn checkout_config_overrides_managed_root_config() {
        let td = TempDir::new().unwrap();
        let checkout = td.path().join("feature");
        fs::create_dir_all(&checkout).unwrap();
        fs::write(
            td.path().join(".wrt.json"),
            r#"{
  "version": 1,
  "port_block_size": 100,
  "package_manager": { "name": "unknown", "install_command": ["npm","install"], "notes": null },
  "services": [{ "name": "web app", "kind": "web", "dev_command": ["npm","run","dev"], "base_port": 3000, "port_env": "PORT", "url_env": "APP_URL", "notes": null }],
  "database": { "detected": false, "kind": null, "migrate_command": null, "seed_command": null, "reset_command": null, "notes": null },
  "supabase": { "detected": false, "config_path": null, "start_command": null, "base_ports": null, "notes": null },
  "notes": null
}
"#,
        )
        .unwrap();
        fs::write(
            checkout.join(".wrt.json"),
            r#"{
  "version": 1,
  "port_block_size": 100,
  "package_manager": { "name": "unknown", "install_command": ["npm","install"], "notes": null },
  "services": [{ "name": "web app", "kind": "web", "dev_command": ["npm","run","dev"], "base_port": 4000, "port_env": "PORT", "url_env": "APP_URL", "notes": null }],
  "database": { "detected": false, "kind": null, "migrate_command": null, "seed_command": null, "reset_command": null, "notes": null },
  "supabase": { "detected": false, "config_path": null, "start_command": null, "base_ports": null, "notes": null },
  "notes": null
}
"#,
        )
        .unwrap();

        let vars = vars(&repo(td.path()), &State::empty(), &alloc(&checkout)).unwrap();
        assert_eq!(vars.get("PORT").unwrap(), "4100");
        assert_eq!(vars.get("APP_URL").unwrap(), "http://localhost:4100");
    }

    #[test]
    fn managed_supabase_env_block_is_idempotent_and_removable() {
        let td = TempDir::new().unwrap();
        let path = td.path().join(".env");
        fs::write(&path, "EXISTING=value\n").unwrap();
        let vars = BTreeMap::from([
            (
                "SUPABASE_URL".to_string(),
                "http://127.0.0.1:54321".to_string(),
            ),
            ("SUPABASE_ANON_KEY".to_string(), "anon".to_string()),
        ]);

        write_managed_block(&path, &vars).unwrap();
        write_managed_block(&path, &vars).unwrap();
        let output = fs::read_to_string(&path).unwrap();
        assert_eq!(output.matches(SUPABASE_BLOCK_START).count(), 1);
        assert!(output.contains("EXISTING=value"));
        assert!(output.contains("SUPABASE_ANON_KEY='anon'"));

        remove_managed_block(&path).unwrap();
        let output = fs::read_to_string(path).unwrap();
        assert_eq!(output, "EXISTING=value\n");
    }
}
